AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a simple Lambda function

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-simple-lambda
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: arn:aws:iam::243599567017:role/LambdaRoleWithAdminAccess  # Replace with your IAM role ARN
      Code:
        S3Bucket: PLACEHOLDER_BUCKET     # Will be filled by `aws cloudformation package`
        S3Key: PLACEHOLDER_KEY           # Will be filled by `aws cloudformation package`
      Timeout: 5
      MemorySize: 128
